### ISSUE TITLE
Background image render issue

### ISSUE THREAD

**Issue by Novtopro** [radkovo/WebVector#6]
<img width="746" alt="2" src="https://user-images.githubusercontent.com/7251140/73381511-dc1a6600-4300-11ea-8fb8-e5f88766eaa5.png">

The web above renders as below, I don't know why

<img width="512" alt="1" src="https://user-images.githubusercontent.com/7251140/73381523-e0df1a00-4300-11ea-9f30-a5f66db4abfa.png">

**Comment by radkovo** [comment]
This is more related to CSSBoxSvg, see radkovo/CSSBoxSvg#1.
